배포 워크플로우에서 현재 브랜치 유효성 검사 추가 및 관련 환경 변수 수정

diff --git a/.github/workflows/deploy.yaml b/.github/workflows/deploy.yaml
--- a/.github/workflows/deploy.yaml
+++ b/.github/workflows/deploy.yaml
@@ -39,12 +39,21 @@ jobs:
       S3_BUCKET_NAME: ${{ needs.validation.outputs.S3_BUCKET_NAME }}
       SERVICE_NAME: ${{ github.event.inputs.SERVICE_NAME }}
       DEPLOY_ENV: ${{ github.event.inputs.DEPLOY_ENV }}
+      CURRENT_BRANCH: ${{ github.ref_name }}
 
       # NOTE: 서비스별 환경 변수 목록. Secrets에 저장된 환경 변수 이름을 작성
       ENV_MOVERANKING_DEV: ${{ secrets.ENV_MOVERANKING_DEV }}
       ENV_CARINSPECTION_DEV: ${{ secrets.ENV_CARINSPECTION_DEV }}
 
     steps:
+      - name: "🔍 배포 브랜치 유효성 검사"
+        run: |
+          if [[ ! ",$AUTHORIZED_BRANCHES," =~ ",$CURRENT_BRANCH," ]]; then
+            printf "::error:: 🚨 지원되지 않는 브랜치입니다: $CURRENT_BRANCH\n"
+            exit 1
+          fi
+          printf "::notice:: ✅ 브랜치 '$CURRENT_BRANCH'는 배포에 유효합니다.\n"
+
       - name: "🔑 AWS IAM KEY 설정"
         run: |
           echo "AWS_ACCESS_KEY_ID=${{ secrets.AWS_ACCESS_KEY_ID }}" >> $GITHUB_ENV
