deploy.yml echo 코드 수정

diff --git a/.github/workflows/deploy.yml b/.github/workflows/deploy.yml
--- a/.github/workflows/deploy.yml
+++ b/.github/workflows/deploy.yml
@@ -107,7 +107,6 @@ jobs:
 
           aws s3 cp s3://$S3_ENV_BUCKET/$FILE_PATH .env --region $S3_REGION
           echo "🚀 $FILE_PATH file downloaded and saved as '.env'."
-          ls -al
 
       # .env 파일 확인
       - name: Verify .env file
@@ -130,7 +129,10 @@ jobs:
       # React Build
       - name: Build
         run: |
-          ls -al
+          if [[ ! -f ".env" ]]; then
+            echo "🚨 .env file is missing! Cannot proceed with the build."
+            exit 1
+          fi
           set -a # 모든 export된 변수 자동 적용
           source .env # .env 파일의 내용을 환경 변수로 로드
           npm run build
