deploy.yml .env 파일 존재 확인

diff --git a/.github/workflows/deploy.yml b/.github/workflows/deploy.yml
--- a/.github/workflows/deploy.yml
+++ b/.github/workflows/deploy.yml
@@ -108,6 +108,16 @@ jobs:
           aws s3 cp s3://$S3_ENV_BUCKET/$FILE_PATH .env --region $S3_REGION
           echo "🚀 $FILE_PATH file downloaded and saved as '.env'."
 
+      # .env 파일 확인
+      - name: Verify .env file
+        run: |
+          if [[ ! -f ".env" ]]; then
+            echo "🚨 .env file is missing!"
+            exit 1
+          fi
+          echo "✅ .env file exists:"
+          cat .env
+
       # 레포지토리 체크아웃
       - name: Checkout source code
         uses: actions/checkout@v3
