필요 없는 로직 삭제 순서 변경

diff --git a/.github/workflows/deployCoconut.yml b/.github/workflows/deployCoconut.yml
--- a/.github/workflows/deployCoconut.yml
+++ b/.github/workflows/deployCoconut.yml
@@ -24,14 +24,6 @@ jobs:
       AWS_SECRET_ACCESS_KEY: ${{ secrets.COCONUT_AWS_SECRET_ACCESS_KEY }} # NOTE: IAM Secret Access Key
 
     steps:
-      # NOTE: 필수 입력 값 확인
-      - name: Check required inputs
-        run: |
-          if [ -z "${{ github.event.inputs.SERVICE_NAME }}" ]; then
-            echo "🚨 ::error:: SERVICE_NAME input is required"
-            exit 1
-          fi
-
       # NOTE: github actions env 설정
       - name: Set github actions env
         run: |
@@ -40,6 +32,20 @@ jobs:
 
           echo "✅ Set env in github actions 'SERVICE_NAME' is '$SERVICE_NAME'"
           echo "✅ Set env in github actions 'CURRENT_BRANCH' is '$CURRENT_BRANCH'"
+
+      # NOTE: 배포 실행 브랜치, 유효성 검사. main, develop 브랜치만 배포 가능
+      - name: Check branch is valid
+        id: validate_branch
+        run: |
+          CURRENT_BRANCH=$(echo "${{ github.ref_name }}")
+          echo "🚀 Current branch: $CURRENT_BRANCH"
+
+          if [[ "$CURRENT_BRANCH" != "$GITHUB_DEV_BRANCH" && "$CURRENT_BRANCH" != "$GITHUB_PROD_BRANCH" ]]; then
+            echo "🚨 ::error:: Unsupported branch: $CURRENT_BRANCH"
+            exit 1
+          fi
+
+          echo "CURRENT_BRANCH=$CURRENT_BRANCH" >> $GITHUB_ENV
 
       # NOTE: 접근할 배포 S3 버킷 설정
       - name: Set deployment S3 bucket
@@ -56,21 +62,7 @@ jobs:
           echo "S3_DEPLOY_BUCKET_NAME=${S3_DEPLOY_BUCKET_PREFIX}-${S3_DEPLOY_BUCKET_SUFFIX}" >> $GITHUB_ENV
           echo "✅ S3 bucket for service '$SERVICE_NAME' is '$S3_DEPLOY_BUCKET_NAME'"
 
-      # NOTE: 배포 실행 브랜치, 유효성 검사. main, develop 브랜치만 배포 가능
-      - name: Check branch is valid
-        id: validate_branch
-        run: |
-          CURRENT_BRANCH=$(echo "${{ github.ref_name }}")
-          echo "🚀 Current branch: $CURRENT_BRANCH"
-
-          if [[ "$CURRENT_BRANCH" != "$GITHUB_DEV_BRANCH" && "$CURRENT_BRANCH" != "$GITHUB_PROD_BRANCH" ]]; then
-            echo "🚨 ::error:: Unsupported branch: $CURRENT_BRANCH"
-            exit 1
-          fi
-
-          echo "CURRENT_BRANCH=$CURRENT_BRANCH" >> $GITHUB_ENV
-
-          # NOTE: 배포 실행 브랜치 및 권한 검증
+      # NOTE: 배포 실행 브랜치 및 권한 검증
       - name: Validate branch and authorization
         run: |
           AUTHORIZED_USERS=$([[ "$CURRENT_BRANCH" == "$GITHUB_DEV_BRANCH" ]] && echo "$AUTHORIZED_USERS_IN_DEV" || echo "$AUTHORIZED_USERS_IN_PROD")
