.yml develop 브랜치 아닐 시, 오류 받도록 함

diff --git a/.github/workflows/gh_trigger.yml b/.github/workflows/gh_trigger.yml
--- a/.github/workflows/gh_trigger.yml
+++ b/.github/workflows/gh_trigger.yml
@@ -6,7 +6,14 @@ on:
 jobs:
   run-job:
     runs-on: ubuntu-latest # 워크플로를 실행할 환경 설정
-    if: ${{ github.ref == 'refs/heads/develop' }} # 브랜치가 develop일 때만 실행
     steps:
-      - name: Print message
+      - name: Check branch condition
+        if: ${{ github.ref != 'refs/heads/develop' }} # 브랜치가 develop이 아닐 때 실행
+        run: |
+          echo "::error::This workflow can only be triggered from the 'develop' branch."
+          exit 1
+
+      # develop 브랜치 조건 만족 시 실행
+      - name: Perform tasks
+        if: ${{ github.ref == 'refs/heads/develop' }} # 브랜치가 develop일 때 실행
         run: echo "Workflow triggered by ${{ github.actor }}"
