printf 코드 수정 및 테스트 불요 코드 주석 처리

diff --git a/.github/workflows/invalidCacheCoconut.yml b/.github/workflows/invalidCacheCoconut.yml
--- a/.github/workflows/invalidCacheCoconut.yml
+++ b/.github/workflows/invalidCacheCoconut.yml
@@ -32,69 +32,70 @@ jobs:
         uses: actions/download-artifact@v4
         with:
           name: shared-variables
-          path: .
+      - run: |
+          ls -R shared-variables
 
-      # NOTE: github actions env 설정
-      - name: Set github actions env
-        run: |
-          if [ "${{ github.event_name }}" == "workflow_dispatch" ]; then
-            SERVICE_NAME="${{ github.event.inputs.SERVICE_NAME }}"
-            DEPLOY_ENV="${{ github.event.inputs.DEPLOY_ENV }}"
-            printf "🚀 내부\n"
-          elif [ "${{ github.event_name }}" == "workflow_run" ]; then
-            SERVICE_NAME=$(jq -r '.SERVICE_NAME' variable.json)
-            DEPLOY_ENV=$(jq -r '.DEPLOY_ENV' variable.json)
-            printf "🚀 외부\n"
-          fi
+      # # NOTE: github actions env 설정
+      # - name: Set github actions env
+      #   run: |
+      #     if [ "${{ github.event_name }}" == "workflow_dispatch" ]; then
+      #       SERVICE_NAME="${{ github.event.inputs.SERVICE_NAME }}"
+      #       DEPLOY_ENV="${{ github.event.inputs.DEPLOY_ENV }}"
+      #       printf "🚀 내부\n"
+      #     elif [ "${{ github.event_name }}" == "workflow_run" ]; then
+      #       SERVICE_NAME=$(jq -r '.SERVICE_NAME' variable.json)
+      #       DEPLOY_ENV=$(jq -r '.DEPLOY_ENV' variable.json)
+      #       printf "🚀 외부\n"
+      #     fi
 
-          printf "🚀 Service name: $SERVICE_NAME\n"
-          printf "🚀 Deployment environment: $DEPLOY_ENV\n"
+      #     printf "🚀 Service name: $SERVICE_NAME\n"
+      #     printf "🚀 Deployment environment: $DEPLOY_ENV\n"
 
-          echo "SERVICE_NAME=${SERVICE_NAME}" >> $GITHUB_ENV
-          echo "DEPLOY_ENV=${DEPLOY_ENV}" >> $GITHUB_ENV
+      #     echo "SERVICE_NAME=${SERVICE_NAME}" >> $GITHUB_ENV
+      #     echo "DEPLOY_ENV=${DEPLOY_ENV}" >> $GITHUB_ENV
 
-          printf "✅ Set env in github actions 'SERVICE_NAME' is '${SERVICE_NAME}'\n"
-          printf "✅ Set env in github actions 'DEPLOY_ENV' is '${DEPLOY_ENV}'\n"
+      #     printf "✅ Set env in github actions 'SERVICE_NAME' is '${SERVICE_NAME}'\n"
+      #     printf "✅ Set env in github actions 'DEPLOY_ENV' is '${DEPLOY_ENV}'\n"
 
-      # NOTE: 배포 실행 환경 변수 명 검사
-      - name: Check deploy environment is valid
-        run: |
-          if [[ "$DEPLOY_ENV" != "dev" && "$DEPLOY_ENV" != "prod" ]]; then
-            printf "🚨 ::error:: Unsupported deploy environment: $DEPLOY_ENV\n"
-            exit 1
-          fi
+      # # NOTE: 배포 실행 환경 변수 명 검사
+      # - name: Check deploy environment is valid
+      #   run: |
+      #     if [[ "$DEPLOY_ENV" != "dev" && "$DEPLOY_ENV" != "prod" ]]; then
+      #       printf "🚨 ::error:: Unsupported deploy environment: $DEPLOY_ENV\n"
+      #       exit 1
+      #     fi
 
-      # NOTE: 배포 실행 환경에 대한 계정 권한 검증
-      - name: Validate authorization
-        run: |
-          AUTHORIZED_USERS=$([[ "$DEPLOY_ENV" == "dev" ]] && echo "$AUTHORIZED_USERS_IN_DEV" || echo "$AUTHORIZED_USERS_IN_PROD")
+      # # NOTE: 배포 실행 환경에 대한 계정 권한 검증
+      # - name: Validate authorization
+      #   run: |
+      #     AUTHORIZED_USERS=$([[ "$DEPLOY_ENV" == "dev" ]] && echo "$AUTHORIZED_USERS_IN_DEV" || echo "$AUTHORIZED_USERS_IN_PROD")
 
-          if [[ ! ",$AUTHORIZED_USERS," =~ ",${{ github.actor }}," ]]; then
-            printf "🚨 ::error:: User '${{ github.actor }}' is not authorized to deploy.\n"
-            exit 1
-          fi
+      #     if [[ ! ",$AUTHORIZED_USERS," =~ ",${{ github.actor }}," ]]; then
+      #       printf "🚨 ::error:: User '${{ github.actor }}' is not authorized to deploy.\n"
+      #       exit 1
+      #     fi
 
-          printf "✅ User '${{ github.actor }}' is authorized to deploy to the $DEPLOY_ENV environment.\n"
+      #     printf "✅ User '${{ github.actor }}' is authorized to deploy to the $DEPLOY_ENV environment.\n"
 
-      # NOTE: 접근할 CloudFront 설정 + 접근할 CloudFront 객체 존재 여부 확인
-      - name: Set CloudFront distribution ID + Check CloudFront object existence
-        run: |
-          DISTRIBUTION_ID=$(echo $CLOUD_FRONT_SERVICES | jq -r --arg SERVICE_NAME "$SERVICE_NAME" --arg DEPLOY_ENV "$DEPLOY_ENV" '.[$SERVICE_NAME + "-" + $DEPLOY_ENV]')
+      # # NOTE: 접근할 CloudFront 설정 + 접근할 CloudFront 객체 존재 여부 확인
+      # - name: Set CloudFront distribution ID + Check CloudFront object existence
+      #   run: |
+      #     DISTRIBUTION_ID=$(echo $CLOUD_FRONT_SERVICES | jq -r --arg SERVICE_NAME "$SERVICE_NAME" --arg DEPLOY_ENV "$DEPLOY_ENV" '.[$SERVICE_NAME + "-" + $DEPLOY_ENV]')
 
-          if [ -z "$DISTRIBUTION_ID" ]; then
-            printf "🚨 ::error:: No CloudFront distribution ID found for service '$SERVICE_NAME' and environment '$DEPLOY_ENV'\n"
-            exit 1
-          fi
+      #     if [ -z "$DISTRIBUTION_ID" ]; then
+      #       printf "🚨 ::error:: No CloudFront distribution ID found for service '$SERVICE_NAME' and environment '$DEPLOY_ENV'\n"
+      #       exit 1
+      #     fi
 
-          echo "DISTRIBUTION_ID=${DISTRIBUTION_ID}" >> $GITHUB_ENV
-          printf "✅ CloudFront distribution '$DISTRIBUTION_ID' is valid.\n"
+      #     echo "DISTRIBUTION_ID=${DISTRIBUTION_ID}" >> $GITHUB_ENV
+      #     printf "✅ CloudFront distribution '$DISTRIBUTION_ID' is valid.\n"
 
-      # NOTE: CloudFront 캐시 무효화 실행
-      - name: Invalidate CloudFront Cache
-        run: |
-          echo "🚀 Invalidating cache for CloudFront distribution: $DISTRIBUTION_ID"
-          aws cloudfront create-invalidation \
-            --distribution-id $DISTRIBUTION_ID \
-            --paths "/*"
+      # # NOTE: CloudFront 캐시 무효화 실행
+      # - name: Invalidate CloudFront Cache
+      #   run: |
+      #     echo "🚀 Invalidating cache for CloudFront distribution: $DISTRIBUTION_ID"
+      #     aws cloudfront create-invalidation \
+      #       --distribution-id $DISTRIBUTION_ID \
+      #       --paths "/*"
 
-          printf "✅ Cache invalidated for distribution ID: $DISTRIBUTION_ID\n"
+      #     printf "✅ Cache invalidated for distribution ID: $DISTRIBUTION_ID\n"
