rollback.yml 로직 수정

diff --git a/.github/workflows/rollback.yml b/.github/workflows/rollback.yml
--- a/.github/workflows/rollback.yml
+++ b/.github/workflows/rollback.yml
@@ -10,7 +10,7 @@ on:
         description: "배포 환경"
         required: true
 
-run-name: "🚀 KOKKOK ${{ inputs.SERVICE_NAME }} / ${{ inputs.DEPLOY_ENV }} 환경 / ${{ github.ref_name }} 브랜치 롤백 실행"
+run-name: "↩️ KOKKOK ${{ inputs.SERVICE_NAME }} / ${{ inputs.DEPLOY_ENV }} 환경 / ${{ github.ref_name }} 브랜치 롤백 실행"
 
 jobs:
   run-job:
@@ -104,7 +104,17 @@ jobs:
 
           printf "::notice:: ✅ 기존 빌드를 build-before로 백업 완료\n"
 
-      - name: "📦 이전 빌드 롤백 (build-before → build) 및 index.html root 경로 업로드"
+      - name: "📦↩️ S3 루트에 index.html 업로드 (기존 build-before/index.html을 최상위로 복사)"
+        run: |
+          # ✅ S3 루트에 index.html 업로드 (기존 build-before/index.html을 최상위로 복사)
+          aws s3 cp --region $S3_DEPLOY_BUCKET_REGION $BUILD_DIR/index.html s3://$S3_BUCKET_NAME/index.html || {
+            printf "::error:: 🚨 S3 루트에 index.html 업로드 실패!\n"
+            exit 1
+          }
+
+          printf "::notice:: ✅ index.html이 S3 루트에 업로드되었습니다: $S3_BUCKET_NAME/index.html\n"
+
+      - name: "📦↩️ 이전 빌드 롤백 (build-before → build) 및 index.html root 경로 업로드"
         run: |
           # ✅ 이전 빌드 파일을 build 폴더로 롤백
           aws s3 mv --recursive --region $S3_DEPLOY_BUCKET_REGION s3://$S3_BUCKET_NAME/build-before s3://$S3_BUCKET_NAME/build || {
@@ -112,12 +122,3 @@ jobs:
           }
 
           printf "::notice:: ✅ 이전 빌드를 build로 롤백 완료\n"
-
-
-          # ✅ S3 루트에 index.html 업로드 (기존 build/index.html을 최상위로 복사)
-          aws s3 cp --region $S3_DEPLOY_BUCKET_REGION $BUILD_DIR/index.html s3://$S3_BUCKET_NAME/index.html || {
-            printf "::error:: 🚨 S3 루트에 index.html 업로드 실패!\n"
-            exit 1
-          }
-
-          printf "::notice:: ✅ index.html이 S3 루트에 업로드되었습니다: $S3_BUCKET_NAME/index.html\n"
