배포 환경 유효성 검사 및 설정 작업의 출력 값을 수정하여 일관성을 개선하고, 코드 가독성을 향상시킴

diff --git a/.github/workflows/validation.yaml b/.github/workflows/validation.yaml
--- a/.github/workflows/validation.yaml
+++ b/.github/workflows/validation.yaml
@@ -1,4 +1,4 @@
-name: Common Workflow
+name: Validate & Setup Env
 
 on:
   workflow_call:
@@ -19,13 +19,13 @@ on:
     outputs:
       AUTHORIZED_BRANCHES:
         description: "배포 가능한 브랜치 목록"
-        value: ${{ jobs.validate-and-configure-deploy.outputs.AUTHORIZED_BRANCHES }}
+        value: ${{ jobs.set-output.outputs.AUTHORIZED_BRANCHES }}
       S3_DEPLOY_BUCKET_REGION:
         description: "배포 S3 버킷이 생성된 리전"
-        value: ${{ jobs.validate-and-configure-deploy.outputs.S3_DEPLOY_BUCKET_REGION }}
+        value: ${{ jobs.set-output.outputs.S3_DEPLOY_BUCKET_REGION }}
       S3_BUCKET_NAME:
         description: "서비스 S3 버킷 이름"
-        value: ${{ jobs.validate-and-configure-deploy.outputs.S3_BUCKET_NAME }}
+        value: ${{ jobs.set-output.outputs.S3_BUCKET_NAME }}
 env:
   AUTHORIZED_ENV: "개발" # NOTE: 배포 가능한 환경 목록. ','로 구분. 띄어쓰기 x
   AUTHORIZED_BRANCHES: "main" # NOTE: 배포 가능한 브랜치 목록. ','로 구분. 띄어쓰기 x
@@ -38,39 +38,17 @@ env:
   S3_DEPLOY_BUCKET_REGION: "ap-southeast-1" # NOTE: 배포 S3 버킷이 생성된 리전
 
 jobs:
-  validate-and-configure-deploy:
+  set-output:
     runs-on: ubuntu-latest
-    env:
-      SERVICE_NAME: ${{ github.event.inputs.SERVICE_NAME }}
-      DEPLOY_ENV: ${{ github.event.inputs.DEPLOY_ENV }}
     outputs:
       AUTHORIZED_BRANCHES: ${{ env.AUTHORIZED_BRANCHES }}
       S3_DEPLOY_BUCKET_REGION: ${{ env.S3_DEPLOY_BUCKET_REGION }}
       S3_BUCKET_NAME: ${{ steps.aws-setting.outputs.S3_BUCKET_NAME }}
     steps:
-      - name: "🛡️ 배포 환경 유효성 검사"
-        run: |
-          if [[ ! ",$AUTHORIZED_ENV," =~ ",$DEPLOY_ENV," ]]; then
-            printf "::error:: 🚨 지원되지 않는 배포 환경입니다: $DEPLOY_ENV\n"
-            exit 1
-          fi
-          printf "::notice:: ✅ 배포 환경 '$DEPLOY_ENV'는 유효합니다.\n"
-
-      - name: "👤 배포 실행 사용자 권한 검증"
-        run: |
-          AUTHORIZED_USERS=$([[ "$DEPLOY_ENV" == "개발" ]] && echo "$AUTHORIZED_USERS_IN_DEV" || echo "")
-
-          if [[ ! ",$AUTHORIZED_USERS," =~ ",${{ github.actor }}," ]]; then
-            printf "::error:: 🚨 사용자 '${{ github.actor }}'는 배포 권한이 없습니다.\n"
-            exit 1
-          fi
-
-          printf "::notice:: ✅ 사용자 '${{ github.actor }}'는 $DEPLOY_ENV 환경에 배포할 권한이 있습니다.\n"
-
       - name: "🛠️ AWS 배포 환경 설정"
         id: aws-setting
         run: |
-          SERVICE_KEY="${SERVICE_NAME}-$([[ "$DEPLOY_ENV" == "개발" ]] && echo "dev" || echo "prod")"
+          SERVICE_KEY="${{ inputs.SERVICE_NAME }}-$([[ "${{ inputs.DEPLOY_ENV }}" == "개발" ]] && echo "dev" || echo "prod")"
 
           # NOTE: 상단에서 미리 작성해둔 AWS_CONFIG > JSON 환경 변수에서 S3 및 CloudFront ID 찾기
           S3_BUCKET_NAME=$(echo "$AWS_CONFIG" | jq -r --arg key "$SERVICE_KEY" '.[$key].s3BucketName')
@@ -82,28 +60,46 @@ jobs:
           fi
 
           # NOTE: 다음 job으로 넘기기 위해 outputs에도 기록
-          echo "AUTHORIZED_BRANCHES=${AUTHORIZED_BRANCHES}" >> $GITHUB_OUTPUT
-          echo "S3_DEPLOY_BUCKET_REGION=${S3_DEPLOY_BUCKET_REGION}" >> $GITHUB_OUTPUT
           echo "S3_BUCKET_NAME=${S3_BUCKET_NAME}" >> $GITHUB_OUTPUT
 
-          printf "::notice:: ✅ 서비스 '$SERVICE_NAME'의 S3 버킷은 '${S3_BUCKET_NAME}'입니다.\n"
+          printf "::notice:: ✅ 서비스 '${{ inputs.SERVICE_NAME }}'의 S3 버킷은 '${S3_BUCKET_NAME}'입니다.\n"
+
+  validate-workflow-config:
+    runs-on: ubuntu-latest
+    needs: set-output
+    steps:
+      - name: "🛡️ 배포 환경 유효성 검사"
+        run: |
+          if [[ ! ",$AUTHORIZED_ENV," =~ ",${{ inputs.DEPLOY_ENV }}," ]]; then
+            printf "::error:: 🚨 지원되지 않는 배포 환경입니다: ${{ inputs.DEPLOY_ENV }}\n"
+            exit 1
+          fi
+          printf "::notice:: ✅ 배포 환경 '${{ inputs.DEPLOY_ENV }}'는 유효합니다.\n"
+
+      - name: "👤 배포 실행 사용자 권한 검증"
+        run: |
+          AUTHORIZED_USERS=$([[ "${{ inputs.DEPLOY_ENV }}" == "개발" ]] && echo "$AUTHORIZED_USERS_IN_DEV" || echo "$AUTHORIZED_USERS_IN_PROD")
+
+          if [[ ! ",$AUTHORIZED_USERS," =~ ",${{ github.actor }}," ]]; then
+            printf "::error:: 🚨 사용자 '${{ github.actor }}'는 배포 권한이 없습니다.\n"
+            exit 1
+          fi
+
+          printf "::notice:: ✅ 사용자 '${{ github.actor }}'는 ${{ inputs.DEPLOY_ENV }} 환경에 배포할 권한이 있습니다.\n"
 
   validate-aws:
     runs-on: ubuntu-latest
-    needs: validate-and-configure-deploy
-    env:
-      S3_BUCKET_NAME: ${{ needs.validate-and-configure-deploy.outputs.S3_BUCKET_NAME }}
+    needs: [set-output, validate-workflow-config]
     steps:
       - name: "🪪 AWS IAM KEY 설정"
         run: |
           echo "AWS_ACCESS_KEY_ID=${{ secrets.AWS_ACCESS_KEY_ID }}" >> $GITHUB_ENV
           echo "AWS_SECRET_ACCESS_KEY=${{ secrets.AWS_SECRET_ACCESS_KEY }}" >> $GITHUB_ENV
           printf "::notice:: ✅ AWS IAM KEY 설정이 완료되었습니다.\n"
-
       - name: "🔎 S3 버킷 존재 여부 확인"
         run: |
-          aws s3api head-bucket --bucket $S3_BUCKET_NAME --region $S3_DEPLOY_BUCKET_REGION || {
-            printf "::error:: 🚨 S3 버킷 '$S3_BUCKET_NAME'이 존재하지 않습니다.\n"
+          aws s3api head-bucket --bucket ${{ needs.set-output.outputs.S3_BUCKET_NAME }} --region ${{ env.S3_DEPLOY_BUCKET_REGION }} || {
+            printf "::error:: 🚨 S3 버킷 '${{ needs.set-output.outputs.S3_BUCKET_NAME }}'이 존재하지 않습니다.\n"
             exit 1
           }
-          printf "::notice:: ✅ S3 버킷 '$S3_BUCKET_NAME'에 접근할 수 있습니다.\n"
+          printf "::notice:: ✅ S3 버킷 '${{ needs.set-output.outputs.S3_BUCKET_NAME }}'에 접근할 수 있습니다.\n"
